# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 840b0d55dc08b6d9d01e0fee69be5bccad1e4be4281e74bac0d298ce136f0db8084b6bffbb301b8729ab5d4a720d75b875e41fdd03be2ee05941d63a0fb341f6

test:
  secret_key_base: 5cecce895de992a8f240529af1b10a5e2a617a104ea54a895678bcb7fecec3c497cf6af62a5f4477abceadbe1086c29abc7c7ae13026b23b75f50d18efc9789e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
